myrecommendations-web2-html/myrecommendations/urls.py
from django.urls import path, include
from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.views.static import serve
from django.conf import settings
from django.views.generic import TemplateView


urlpatterns = [
    path('', include('myrestaurants.urls')),
    path('admin/', admin.site.urls),
    path('accounts/login/', auth_views.LoginView.as_view(), name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(), name='logout'),
]

if settings.DEBUG:
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT, })
    ]

myrecommendations-web2-html/myrestaurants/urls.py
from django.conf.urls import url
from django.urls import path
from django.utils import timezone
from django.views.generic import DetailView, ListView, UpdateView
from .models import Restaurant,Dish,RestaurantReview
from .forms import RestaurantForm, DishForm
from .views import RestaurantCreate, DishCreate, RestaurantDetail, review, UpdateRestaurant

app_name = 'myrestaurants'

urlpatterns = [
    # List latest 5 restaurants: /myrestaurants/
    url(r'^$',
        ListView.as_view(
            queryset=Restaurant.objects.all().order_by('date')[:5],
            context_object_name='latest_restaurant_list',
            template_name='myrestaurants/restaurant_list.html'),
        name='restaurant_list'),

    # Restaurant details, ex.: /myrestaurants/restaurants/1/
    url(r'^restaurants/(?P<pk>\d+)/$',
        RestaurantDetail.as_view(),
        name='restaurant_detail'),

    # Restaurant dish details, ex: /myrestaurants/restaurants/1/dishes/1/
    url(r'^restaurants/(?P<pkr>\d+)/dishes/(?P<pk>\d+)/$',
        DetailView.as_view(
            model=Dish,
            template_name='myrestaurants/dish_detail.html'),
        name='dish_detail'),

    # Create a restaurant, /myrestaurants/restaurants/create/
    url(r'^restaurants/create/$',
        RestaurantCreate.as_view(),
        name='restaurant_create'),

    # Edit restaurant details, ex.: /myrestaurants/restaurants/1/edit/
    url(r'^restaurants/(?P<pk>\d+)/edit/$',
        UpdateView.as_view(
            model=Restaurant,
            template_name='myrestaurants/form.html',
            form_class=RestaurantForm),
        name='restaurant_edit'),

    # Create a restaurant dish, ex.: /myrestaurants/restaurants/1/dishes/create/
    url(r'^restaurants/(?P<pk>\d+)/dishes/create/$',
        DishCreate.as_view(),
        name='dish_create'),

    # Edit restaurant dish details, ex.: /myrestaurants/restaurants/1/dishes/1/edit/
    # url(r'^restaurants/(?P<pkr>\d+)/dishes/(?P<pk>\d+)/edit/$',
    #     UpdateView.as_view(
    #         ),
    #     name='dish_edit'),
    url(r'^restaurants/(?P<pkr>\d+)/dishes/(?P<pk>\d+)/edit/$', UpdateRestaurant.as_view(), name='dish_edit'),

    # Create a restaurant review, ex.: /myrestaurants/restaurants/1/reviews/create/
    url(r'^restaurants/(?P<pk>\d+)/reviews/create/$',
        review,
        name='review_create'),
]

myrecommendations-web2-html/myrestaurants/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from datetime import date

class Restaurant(models.Model):
    name = models.CharField(max_length=255)
    street = models.CharField(max_length=255, blank=True, null=True)
    number = models.IntegerField(blank=True, null=True)
    city = models.CharField(max_length=255, default="")
    zipCode = models.CharField(max_length=255, blank=True, null=True)
    stateOrProvince = models.CharField(max_length=255, blank=True, null=True)
    country = models.CharField(max_length=255, blank=True, null=True)
    telephone = models.CharField(max_length=255, blank=True, null=True)
    url = models.URLField(blank=True, null=True)
    user = models.ForeignKey(User,on_delete=models.PROTECT)
    date = models.DateField(default=date.today)

    def __unicode__(self):
        return u"%s" % self.name
    def get_absolute_url(self):
        return reverse('myrestaurants:restaurant_detail', kwargs={'pk': self.pk})
    def __str__(self):
        return self.name

class Dish(models.Model):
    name = models.TextField()
    description = models.TextField(blank=True, null=True)
    price = models.DecimalField('Euro amount', max_digits=8, decimal_places=2, blank=True,
        null=True)
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    date = models.DateField(default=date.today)
    image = models.ImageField(upload_to="myrestaurants", blank=True, null=True)
    restaurant = models.ForeignKey('Restaurant', on_delete=models.PROTECT, related_name='dishes')

    def __unicode__(self):
        return u"%s" % self.name
    def get_absolute_url(self):
        return reverse('myrestaurants:dish_detail', kwargs={'pkr': self.restaurant.pk, 'pk': self.pk})
    def __str__(self):
        return self.name

class Review(models.Model):
    RATING_CHOICES = ((1, 'one'), (2, 'two'), (3, 'three'), (4, 'four'), (5, 'five'))
    rating = models.PositiveSmallIntegerField('Rating (stars)', blank=False, default=3, choices=RATING_CHOICES)
    comment = models.TextField(blank=True, null=True)
    user = models.ForeignKey(User,on_delete=models.PROTECT)
    date = models.DateField(default=date.today)

    class Meta:
        abstract = True

class RestaurantReview(Review):
    restaurant = models.ForeignKey('Restaurant',on_delete=models.PROTECT)

myrecommendations-web2-html/myrestaurants/forms.py
from django.forms import ModelForm
from .models import Restaurant, Dish

class RestaurantForm(ModelForm):
    class Meta:
        model = Restaurant
        exclude = ('user', 'date',)

class DishForm(ModelForm):
    class Meta:
        model = Dish
        exclude = ('user', 'date', 'restaurant',)

myrecommendations-web2-html/myrestaurants/views.py
from django.shortcuts import render
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.views.generic import DetailView
from django.views.generic.edit import CreateView, UpdateView
from .models import RestaurantReview, Restaurant, Dish
from .forms import RestaurantForm, DishForm
from django.views.generic import TemplateView

#pour affichage de detail d'un restaurant
class RestaurantDetail(DetailView):
    model = Restaurant
    template_name = 'myrestaurants/restaurant_detail.html'

    def get_context_data(self, **kwargs):
        context = super(RestaurantDetail, self).get_context_data(**kwargs)
        context['RATING_CHOICES'] = RestaurantReview.RATING_CHOICES
        return context
#pour generer des formulaire
class RestaurantCreate(CreateView):
    model = Restaurant
    template_name = 'myrestaurants/form.html'
    form_class = RestaurantForm
    
    #pour montrer ce qui est dans navbar
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_title'] = "Create Restaurant"
        context['latest_restaurant_list'] = Restaurant.objects.all().order_by('date')[:5]
        return context

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(RestaurantCreate, self).form_valid(form)

# creation des plats
class DishCreate(CreateView):
    model = Dish
    template_name = 'myrestaurants/form.html'
    form_class = DishForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_title'] = "Create Dish"
        context['latest_restaurant_list'] = Restaurant.objects.all().order_by('date')[:5]
        return context

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.restaurant = Restaurant.objects.get(id=self.kwargs['pk'])
        return super(DishCreate, self).form_valid(form)

# Modification de restaurant
class UpdateRestaurant(UpdateView):
    model = Dish,
    template_name = 'myrestaurants/form.html',
    form_class = DishForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_title'] = "Edit Restaurant"
        context['latest_restaurant_list'] = Restaurant.objects.all().order_by('date')[:5]
        return context

def review(request, pk):
    restaurant = get_object_or_404(Restaurant, pk=pk)
    review = RestaurantReview(
        rating=request.POST['rating'],
        comment=request.POST['comment'],
        user=request.user,
        restaurant=restaurant)
    review.save()
    return HttpResponseRedirect(reverse('myrestaurants:restaurant_detail', args=(restaurant.id,)))

myrecommendations-web2-html/myrestaurants/templates/myrestaurants/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.css" integrity="sha256-9mbkOfVho3ZPXfM7W8sV2SndrGDuh7wuyLjtsWeTI1Q=" crossorigin="anonymous" />
    <link rel="stylesheet" href="{% static 'css/base.css' %}" />
    <link rel="icon" href="{% static 'img/favicon.png' %}" />
    <title>{% block title %}MyRestaurants by MyRecommentdations.org{% endblock %}</title>
</head>
<body>
<div id="header">
    {% block header %}
        <!-- {% if user.username %}
            <p>User: {{ user.username }} | <a href="{% url 'logout' %}?next={{request.path}}">logout</a></p>
        {% else %}
            <p><a href="{% url 'login' %}?next={{request.path}}">login</a></p>{% endif %} -->
    {% endblock %}
</div>
<div id="content">
    {% block content %}
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    {% endblock %}
</div>
<div id="footer">{% block footer %}{% endblock %}</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.js" integrity="sha256-t8GepnyPmw9t+foMh3mKNvcorqNHamSKtKRxxpUEgFI=" crossorigin="anonymous"></script>
<script src="{% static 'js/app.js' %}"></script>    
</body>
</html>

myrecommendations-web2-html/myrestaurants/templates/myrestaurants/dish_detail.html
{% extends "myrestaurants/base.html" %}

{% block content %}

<h1>
    {{ dish.name }}
    {% if user == dish.user %}
        (<a href="{% url 'myrestaurants:dish_edit' dish.restaurant.id dish.id %}">edit</a>)
    {% endif %}
</h1>
<p>{{ dish.description }}</p>
{% if dish.image %}
    <p><img src="{{ dish.image.url }}"/></p>
{% endif %}
<p>Served by <a href="{% url 'myrestaurants:restaurant_detail' dish.restaurant.id %}">{{ dish.restaurant.name }}</a></p>

{% endblock %}

{% block footer %}
    Created by {{ dish.user }} on {{ dish.date }}
{% endblock %}

myrecommendations-web2-html/myrestaurants/templates/myrestaurants/form.html
{% extends "myrestaurants/base.html" %}
{% load static %}

{% block title %}{{page_title}}{% endblock title %}
    
{% block header %}
<div class="ui inverted fixed menu">
    <div class="header item">
        <a href="/"><h2><i class="utensils icon"></i>Restaurants</h2></a>
    </div>
    <div class="right menu">
        <div class="ui dropdown item">
            <i class="list alternate outline icon"></i> Restaurants List
            <i class="dropdown icon"></i>
            <div class="menu">
                {% for restaurant in latest_restaurant_list %}
                    <li class="item"><a href="{% url 'myrestaurants:restaurant_detail' restaurant.id %}" style="color: black;">{{ restaurant.name }}</a></li>
                {% empty %}<li class="item">Sorry, no restaurants registered yet.</li>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock header %}
        
{% block content %}
    <div class="ui inverted vertical masthead center aligned segment" id="main">
        <div class="ui text container">
            <div class="ui middle aligned center aligned grid">
                <div class="column">
                    <h2 class="ui inverted image header">
                        <div class="content"></div>
                    </h2>
                    <form class="ui large form" method="post" enctype="multipart/form-data" action="">
                        {% csrf_token %}
                        <div class="ui stacked segment">
                            {% for field in form %}
                                <div class="field">
                                    <div class="ui input">
                                        <div class="ui label">
                                            <i class="pencil alternate icon"></i> {{ field.label_tag }}
                                        </div>
                                        {{ field }}
                                    </div>
                                </div>
                            {% endfor %}

                            <input class="ui fluid large brown submit button" type="submit" value="Submit" />
                        </div>
                        {% if form.errors %}
                            <div class="ui error message" style="display: block;">Your username and password didn't match. Please try again.</div>
                        {% endif %}
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

myrecommendations-web2-html/myrestaurants/templates/myrestaurants/restaurant_detail.html
{% extends "myrestaurants/base.html" %}
{% load static %}

{% block title %}{{page_title}}{% endblock title %}
    
{% block header %}
<div class="ui inverted fixed menu">
    <div class="header item">
        <a href="/"><h2><i class="utensils icon"></i>Restaurants</h2></a>
    </div>
    <div class="right menu">
        <div class="item">
         {{ restaurant.name }}
        {% if user == restaurant.user %}
        <a   href="{% url 'myrestaurants:restaurant_edit' restaurant.id %}"><i class="info circle icon"></i> edit restaurant</a>
        {% endif %}

        {% if user %}
       <a href="{% url 'myrestaurants:dish_create' restaurant.id %}"><i class="plus circle icon"></i>add dish</a>
        {% endif %}
    </div>
</div>
            
</div>
{% endblock header %}
        
{% block content %}

    <div class="ui inverted vertical masthead center aligned segment" id="main">
        <div class="ui text container">
            <div class="ui middle aligned center aligned grid">
                <div class="column">
                    <h2 class="ui inverted image header">
                        <div class="content">
                          <div class="jumbotron jumbotron-fluid bg-primary py-6  mt-5">
                        <div class="container">
                        <h1 class="text-white"></h1>
                        <div class="lead text-white">
                           
                        </div>
                         </div>
                       </div>
                    </div>
                    
                    <form class="ui large form" method="post" enctype="multipart/form-data" action="{% url 'myrestaurants:review_create' restaurant.id %}">
                        {% csrf_token %}
                        <div class="ui stacked segment">
                            {% for field in form %}
                                <div class="field">
                                    <div class="ui input">
                                        <div class="ui label">
                                            <i class="pencil alternate icon"></i> {{ field.label_tag }}
                                        </div>
                                        {{ field }}
                                    </div>
                                </div>
                            {% endfor %}
                            {{ restaurant.street }}, {{ restaurant.number }}<br/> 
                            {{ restaurant.zipcode }} {{ restaurant.city }} 
                            {{ restaurant.stateOrProvince }} ({{ restaurant.country }})
                            {% for dish in restaurant.dishes.all %}
                            <li><a href="{% url 'myrestaurants:dish_detail' restaurant.id dish.id %}">
                                {{ dish.name }}</a></li>
                            {% empty %}
                           <p>Sorry, no dishes for this restaurant yet.</p>
                            {% endfor %}
                            <h2>Reviews</h2>
                            <center>
                            {% for review in restaurant.restaurantreview_set.all %}
                            <p>
                         <p>{{ review.rating }} star{{ review.rating|pluralize }}</p>
                         <p>{{ review.comment }}</p>
                        <p>Created by {{ review.user }} on {{ review.date }}</p>
                         </p>
                         {% endfor %}
                          </center>
                            Message: <textarea name="comment" id="comment" rows="4"></textarea>
                            <p>Rating:</p>
                             <p>{% for rate in RATING_CHOICES %}
                            <input type="radio" name="rating" id="rating{{ forloop.counter }}" value="{{ rate.0 }}" />
                            <label for="choice{{ forloop.counter }}">{{ rate.1 }} star{{ rate.0|pluralize }}</label>
                           <br/>{% endfor %}
                         </p>
                        
                        <input class="ui fluid large brown submit button" type="submit" value="Review" />
                    </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

myrecommendations-web2-html/myrestaurants/templates/myrestaurants/restaurant_list.html
{% extends "myrestaurants/base.html" %}
{% load static %}

{% block title %}Home{% endblock title %}
    
{% block header %}
<div class="ui inverted fixed menu">
    <div class="header item">
        <a href="/"><h2><i class="utensils icon"></i>Restaurants</h2></a>
    </div>
    <div class="right menu">
        <a class="active item link" href="#main"><i class="home icon"></i> Home</a>
        <a class="item link" href="#about"><i class="info circle icon"></i> About</a>
        {% if user.is_authenticated %}
            <a class="item" href="/restaurants/create/"><i class="plus circle icon"></i> Add Restaurant</a>
            <div class="ui dropdown item">
                <i class="list alternate outline icon"></i> Restaurants List
                <i class="dropdown icon"></i>
                <div class="menu">
                    {% for restaurant in latest_restaurant_list %}
                        <li class="item"><a href="{% url 'myrestaurants:restaurant_detail' restaurant.id %}" style="color: black;">{{ restaurant.name }}</a></li>
                    {% empty %}<li class="item">Sorry, no restaurants registered yet.</li>
                    {% endfor %}
                </div>
            </div>
            <a class="item" href="accounts/logout/"><i class="user circle icon"></i> Sign out</a>
        {% else %}
            <a class="item" href="accounts/login/"><i class="user circle icon"></i> Sign in</a>
        {% endif %}
    </div>
</div>
{% endblock header %}
        
{% block content %}
    <div class="ui inverted vertical masthead center aligned segment" id="main">
        <div class="ui text container">
            <h1 class="ui inverted header main-title">
                Restaurant
            </h1>
            <p class="main-subtitle">" The best restaurants "</p>
            <hr>
        </div>
    </div>
  
    <div class="ui vertical stripe segment" id="about">
        <div class="ui middle aligned stackable grid container">
            <div class="row">
                <div class="center aligned nine wide column">
                    <h1 class="about_title">About us</h1><br>
                    <div class="icon"><i class="big utensils icon"></i></div>
                    <p class="about-desc">
                        Our restaurants offer you good dishes, good juices, good services. you will find everything you want in our restaurants.
                    </p>
                </div>
                <div class="center aligned seven wide column">
                    <div class="pic-group">
                        <img src="{% static 'img/kabob.jpg' %}" width="250" height="220" />
                        <img src="{% static 'img/limes.jpg' %}" width="250" height="220" />
                    </div>
                    <div class="ui divider"></div>
                    <div class="pic-group">
                        <img src="{% static 'img/radish.jpg' %}"  width="250" height="220" />
                        <img src="{% static 'img/corn.jpg' %}"  width="250" height="220" />
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}